clean up various board files; finish out 600C a bit; add auto-config logic for cradlepoints for wifi and root password
Signed-off-by: Natalie Moore <natalie@natalielucy.dev>

diff --git a/target/linux/ipq40xx/base-files/etc/board.d/02_network b/target/linux/ipq40xx/base-files/etc/board.d/02_network
--- a/target/linux/ipq40xx/base-files/etc/board.d/02_network
+++ b/target/linux/ipq40xx/base-files/etc/board.d/02_network
@@ -269,11 +269,55 @@ ipq40xx_setup_macs()
 	[ -n "$label_mac" ] && ucidef_set_label_macaddr $label_mac
 }
 
+
+mtd_get_custdata() {
+	local key="$1"
+
+	part=$(find_mtd_part "0:CUSTDATA")
+	if [ -z "$part" ]; then
+		echo "mtd_get_custdata: partition $mtdname not found!" >&2
+		return
+	fi
+
+	echo -n $(strings "$part" | tr -d ' \t' | sed -n 's/^'"$key"'=//p' | head -n 1)
+}
+
+
+# by default, cradlepoints use the serial for wifi PSK and login password
+# let's replicate this for easier OOBE setup
+
+#TODO: make this a bit more resilient to failure
+cradlepoint_setup()
+{
+	local board="$1"
+
+	case "$board" in
+	cradlepoint,ibr600c |\
+	cradlepoint,ibr900 |\
+	cradlepoint,ibr1700 |\
+	cradlepoint,aer2200)
+		serial=$(mtd_get_custdata "SerialNumber")
+		quasi_uid=$(mtd_get_custdata "MAC0" | cut -c 9-)
+
+		if [ -z "$serial" ] || [ -z "$quasi_uid" ]; then
+			echo "cradlepoint_setup: serial number and/or MAC address were unable to be found! Not configuring root password or wifi..." >&2
+			return
+		fi
+
+		ucidef_set_wireless 2g "OpenWRT-$quasi_uid" sae-mixed "$serial"
+		ucidef_set_wireless 5g "OpenWRT-$quasi_uid-5g" sae-mixed "$serial"
+		ucidef_set_root_password_plain "$serial"
+		;;
+	esac
+}
+
+
 board_config_update
 board=$(board_name)
 ipq40xx_setup_interfaces $board
 ipq40xx_setup_dsl $board
 ipq40xx_setup_macs $board
+cradlepoint_setup $board
 board_config_flush
 
 exit 0
